version: "3"
services:
  simple-docker:
    image: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.6
    ports:
      - "9000:4050"
    environment:
      API_PORT: "4050"
      REDIS_ADDR: "redis:6379"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  redis:
    image: redis:latest
