version: "3"
services:
  simple-docker:
    build:
      context: .
      args:
        HOST: "127.0.0.1"
        PORT: "9000"
    image: simple-docker:latest
    ports:
      - "9000:4050"
    environment:
      API_PORT: "4050"
      REDIS_ADDR: "redis:6379"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  redis:
    image: redis:latest
