# yaml 配置实例
version: '3'
services:
  redis:
    image: redis:latest
  web:
    build: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.5
    ports:
      - "9090:4050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
